name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Triggers the pipeline on every push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checks out the code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Adjust to your programming language or framework

    - name: Install dependencies
      run: npm install  # Install project dependencies (change to your package manager if needed)

    - name: update dependencies
      run: npm update
      
    - name: Run tests
      run: npm test  # Run tests (adjust this command based on your project's needs)

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Runs this job only if the 'build' job succeeds
    if: success()  # Execute this job only if all previous jobs are successful

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Staging
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: '.'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deployed from GitHub Actions"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.API_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
